<main>
    <div class="intro-banner">
        <h1>Tout sur la League</h1>
        <p>Les joueurs, les équipes et l'actu des matchs</p>
    </div>


    <?php
    $teamManager = new TeamManager();
    $playerManager = new PlayerManager();
    $matchManager = new MatchManager();
    $highlightTeam = $teamManager->getRandomTeam();
    $highlightTeamMedia = $teamManager->getMedia($highlightTeam->getId())
    ?>
    <article class="article-equipe">
        <h2 class="yellow-text">L'équipe à la une</h2>
        <div class="team-info">
            <h3 class="yellow-text"><?= $highlightTeam->getName() ?></h3>
            <img src="<?= $highlightTeamMedia->getUrl() ?>" alt="<?= $highlightTeamMedia->getAlt() ?>" />
        </div>
        <div class="team-players">
            <p>Les joueurs</p>
            <div class="team-player-box">
                <?php
                $teammates = $playerManager->getTeammates($highlightTeam->getId());
                foreach ($teammates as $teammate) {
                    $media = $playerManager->getMedia($teammate->getId());
                ?>
                    <div class="team-player-card">

                        <img src="<?= $media->getUrl() ?>" alt="<?= $media->getAlt() ?>" />
                        <p class="player-name"><?= $teammate->getNickname() ?></p>

                    </div>
                <?php
                }
                ?>

            </div>
        </div>
    </article>
    <article class="article-players">
        <h2>Les joueurs à la une</h2>
        <div class="player-box">
            <?php
            $highlightPlayers = $playerManager->get3RandomPlayers();

            foreach ($highlightPlayers as $player) {
                $media = $playerManager->getMedia($player->getId());
                $team = $playerManager->getTeam($player->getId())
            ?>
                <div class="player-card">
                    <img src="<?= $media->getUrl() ?>" alt="<?= $media->getAlt() ?>" />
                    <p class="player-name"><?= $player->getNickname() ?></p>
                    <p class="team-name yellow-text"><?= $team->getName() ?></p>
                    <a class="player-link-button pink-text" href="index.php?route=player&player=<?= $player->getId() ?>">Découvrez <?= $player->getNickname() ?></a>
                </div>
            <?php
            }
            ?>
        </div>
    </article>
    <article class="article-match">
        <h2>Le dernier match</h2>
        <?php
        $latestMatch = $matchManager->getLatestMatch();
        //init teams info and imgs
        $team1 = $matchManager->getTeam1($latestMatch->getId());
        $mediaTeam1 = $teamManager->getMedia($latestMatch->getTeam_1());
        $team2 = $matchManager->getTeam2($latestMatch->getId());
        $mediaTeam2 = $teamManager->getMedia($latestMatch->getTeam_2());
        $winner = $matchManager->getWinner($latestMatch->getId());
        ?>
        <div class="match-images">
            <img <?php
                    //if team1 winner border green 
                    if ($team1 === $winner) {
                        echo "class='match-winner-img'";
                    }
                    ?> src="<?= $mediaTeam1->getUrl() ?>" alt="<?= $mediaTeam1->getAlt() ?>" />
            <div class="match-infos">
                <h3><?= $team1 ?> - <?= $team2 ?></h3>
                <p><?= $latestMatch->getDate() ?></p>
            </div>
            <img <?php
                    //if team1 winner border green 
                    if ($team2 === $winner) {
                        echo "class='match-winner-img'";
                    } ?> src="<?= $mediaTeam2->getUrl() ?>" alt="<?= $mediaTeam2->getAlt() ?>" />
        </div>
    </article>
</main>