<h1 class="pink-text">Les joueurs de la League</h1>

<div class="players-grid">

    <?php
    $playerManager = new PlayerManager();
    foreach ($players as $player) {

        $media = $playerManager->getMedia($player->getId());
        $team = $playerManager->getTeam($player->getId());

    ?>
        <div class="player-card">
            <img src="<?= $media->getUrl() ?>" alt="<?= $media->getAlt() ?>" />
            <p class="player-name"><?= $player->getNickname() ?></p>
            <p class="team-name yellow-text"><?= $team->getName() ?></p>
            <a class="player-link-button pink-text" href="index.php?route=player&player=<?= $player->getId() ?>">Découvrez <?= $player->getNickname() ?></a>
        </div>
    <?php
    }
    ?>

</div>